# Generated by Django 2.1.2 on 2018-10-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='nota',
            field=models.CharField(max_length=200, null=True, verbose_name='Nota'),
        ),
    ]
